Results:
  save_results: True
  save_dir: "results"
  save_trj: True
  save_trj_kf_intv: 20
  use_gui: True
  eval_rendering: True
  use_wandb: False

Dataset:
  sensor_type: 'depth'
  pcd_downsample: 64
  pcd_downsample_init: 32
  adaptive_pointsize: False
  point_size: 0.2
  type: 'replica'
  Calibration:
    fx: 600.0
    fy: 600.0
    cx: 599.5
    cy: 339.5
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 1200
    height: 680
    depth_scale: 6553.5
    distorted: False


Training:
  init_itr_num: 1050
  init_gaussian_update: 100
  init_gaussian_reset: 500
  init_gaussian_th: 0.005
  init_gaussian_extent: 30
  tracking_itr_num: 50
  mapping_itr_num: 150
  gaussian_update_every: 150
  gaussian_update_offset: 50
  gaussian_th: 0.0
  gaussian_extent: 300
  gaussian_reset: 2001
  size_threshold: 1000
  kf_interval: 4
  window_size: 8
  pose_window: 8
  edge_threshold: 4
  rgb_boundary_threshold: 0.01
  init_alpha: 0.9
  alpha: 0.9
  kf_translation: 0.04
  kf_min_translation: 0.02
  kf_overlap: 0.95
  prune_mode: 'slam'
  single_thread: False
  spherical_harmonics: False
  lr:
    cam_rot_delta: 0.003
    cam_trans_delta: 0.001
  opacity_threshold: 0.9
  ratio_threshold: 40
  newframe_init_iter: 10
  front_depth_threshold: 0.01


opt_params:
  iterations: 30000
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.001
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15000

  init_densify_grad_threshold: 0.0002
  densify_grad_threshold: 0.0002

model_params:
  sh_degree: 0
  source_path: ""
  model_path: ""
  resolution: -1
  white_background: False
  data_device: "cuda"
  
pipeline_params:
  convert_SHs_python: False
  compute_cov3D_python: False
